FROM ubuntu:24.04
LABEL maintainer="rick@scriptix.io"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        g++ \
        make \
        automake \
        autoconf \
        bzip2 \
        unzip \
        wget \
        sox \
        libtool \
        git \
        subversion \
        python3 \
        python3-is-python \
        zlib1g-dev \
        ca-certificates \
        gfortran \
        intel-mkl \
        patch \
        ffmpeg \
        vim && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 https://github.com/kaldi-asr/kaldi.git /opt/kaldi
RUN    cd /opt/kaldi/src && \
       ./configure --shared
Run    make depend -j $(nproc)
Run    make -j $(nproc)
Run    find /opt/kaldi -type f \( -name "*.o" -o -name "*.la" -o -name "*.a" \) -exec rm {} \; && \
       find /opt/intel -type f -name "*.a" -exec rm {} \; && \
       find /opt/intel -type f -regex '.*\(_mc.?\|_mic\|_thread\|_ilp64\)\.so' -exec rm {} \; && \
       rm -rf /opt/kaldi/.git
WORKDIR /opt/kaldi/
