FROM ubuntu:24.04 AS base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        g++ \
        make \
        automake \
        autoconf \
        bzip2 \
        unzip \
        wget \
        sox \
        libtool \
        git \
        subversion \
        python3 \
        zlib1g-dev \
        ca-certificates \
        gfortran \
        intel-mkl \
        patch \
        ffmpeg \
        vim && \
    rm -rf /var/lib/apt/lists/*

FROM base AS compiled

RUN git clone --depth 1 https://github.com/kaldi-asr/kaldi.git /opt/kaldi
RUN cd /opt/kaldi/tools && \
        make -j $(nproc --ignore=4) && \
        ./extras/check_dependencies.sh
RUN cd /opt/kaldi/src && \
       ./configure --shared
RUN cd /opt/kaldi/src && \
        make depend -j $(nproc --ignore=4)
RUN cd /opt/kaldi/src && \
        make -j $(nproc --ignore=4)
RUN    find /opt/kaldi -type f \( -name "*.o" -o -name "*.la" -o -name "*.a" \) -delete


FROM base

ENV LANG C.UTF-8
RUN apt update && apt install -y python3-pip
COPY --from=compiled /opt/kaldi /opt/kaldi

WORKDIR /opt/kaldi/
